DEBUG = False
DEBUG_FIND_BASE = False
DEBUG_DISPLAY_IMAGES = False
DEBUG_LOADING_IMAGES = False
RESULT_DISPLAY_RANKING = True
RESULT_DISPLAY_RANKING_POINTS = False
RESULT_DISPLAY_POINTS = True
RESULT_DISPLAY_CORRECT = False
RESULT_DISPLAY_TOTAL_POINTS = True

